# Generated by Django 5.2.4 on 2025-12-28 09:23

import django.db.models.deletion
import mahjong.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=mahjong.models.generate_room_code, editable=False, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uma_1st', models.IntegerField(default=20, verbose_name='1位ウマ')),
                ('uma_2nd', models.IntegerField(default=10, verbose_name='2位ウマ')),
                ('uma_3rd', models.IntegerField(default=-10, verbose_name='3位ウマ')),
                ('uma_4th', models.IntegerField(default=-20, verbose_name='4位ウマ')),
                ('oka', models.IntegerField(default=20, verbose_name='オカ')),
                ('starting_points', models.IntegerField(default=25000, verbose_name='持ち点')),
                ('return_points', models.IntegerField(default=30000, verbose_name='返し点')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='プレイヤー名')),
                ('order', models.IntegerField(verbose_name='順番')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='mahjong.room')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('room', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField(default=1, verbose_name='ゲーム番号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='mahjong.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('room', 'game_number')},
            },
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='持ち点')),
                ('chip_change', models.IntegerField(default=0, verbose_name='チップ増減')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='順位')),
                ('points', models.FloatField(blank=True, null=True, verbose_name='ポイント')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to='mahjong.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to='mahjong.player')),
            ],
            options={
                'ordering': ['rank', 'player__order'],
            },
        ),
    ]
