# Generated by Django 5.2.4 on 2025-12-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='return_points',
        ),
        migrations.RemoveField(
            model_name='room',
            name='uma_1st',
        ),
        migrations.RemoveField(
            model_name='room',
            name='uma_2nd',
        ),
        migrations.RemoveField(
            model_name='room',
            name='uma_3rd',
        ),
        migrations.RemoveField(
            model_name='room',
            name='uma_4th',
        ),
        migrations.AddField(
            model_name='room',
            name='custom_return_points',
            field=models.IntegerField(default=30000, verbose_name='カスタム返し点'),
        ),
        migrations.AddField(
            model_name='room',
            name='rate_type',
            field=models.CharField(choices=[('pin', '点ピン (25000/25000)'), ('5', '点5 (25000/30000)'), ('10', '点10 (25000/35000)'), ('custom', 'カスタム')], default='5', max_length=10, verbose_name='レート'),
        ),
        migrations.AddField(
            model_name='room',
            name='sashi_uma_1_2',
            field=models.IntegerField(default=5, verbose_name='サシウマ1-2位'),
        ),
        migrations.AddField(
            model_name='room',
            name='sashi_uma_3_4',
            field=models.IntegerField(default=10, verbose_name='サシウマ3-4位'),
        ),
    ]
