# Generated by Django 5.2.4 on 2025-12-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0002_remove_room_return_points_remove_room_uma_1st_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rate_type',
            field=models.CharField(choices=[('pin', '点ピン (25000/25000)'), ('5', '点5 (25000/30000)'), ('ryan', '点りゃん (25000/30000)'), ('custom', 'カスタム')], default='5', max_length=10, verbose_name='レート'),
        ),
    ]
