# Generated by Django 5.2.4 on 2025-12-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0003_alter_room_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rate_type',
            field=models.CharField(choices=[('no', 'ノーレート (25000/25000)'), ('ten1', 'テンイチ (25000/26000)'), ('ten2', 'テンニ (25000/27000)'), ('ten3', 'テンサン (25000/28000)'), ('ten5', 'テンゴ (25000/30000)'), ('pin', 'テンピン (25000/35000)'), ('ryanpin', 'テンリャンピン (25000/45000)'), ('upin', 'ウーピン (25000/75000)'), ('dekapin', 'デカピン (25000/125000)'), ('custom', 'カスタム')], default='ten5', max_length=10, verbose_name='レート'),
        ),
    ]
