# Generated by Django 5.2.4 on 2025-12-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0004_alter_room_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chip_point_rate',
            field=models.FloatField(default=1.0, verbose_name='チップ1枚あたりのポイント'),
        ),
    ]
