# Generated by Django 5.2.4 on 2025-12-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0005_room_chip_point_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='sashi_uma_type',
            field=models.CharField(choices=[('5-10', '5-10 (1位+15, 2位+5, 3位-5, 4位-15)'), ('10-20', '10-20 (1位+30, 2位+10, 3位-10, 4位-30)'), ('10-30', '10-30 (1位+40, 2位+10, 3位-10, 4位-40)'), ('custom', 'カスタム')], default='5-10', max_length=10, verbose_name='サシウマタイプ'),
        ),
        migrations.AlterField(
            model_name='room',
            name='sashi_uma_1_2',
            field=models.IntegerField(default=5, verbose_name='サシウマ1-2位（カスタム用）'),
        ),
        migrations.AlterField(
            model_name='room',
            name='sashi_uma_3_4',
            field=models.IntegerField(default=10, verbose_name='サシウマ3-4位（カスタム用）'),
        ),
    ]
