# Generated by Django 5.2.4 on 2025-12-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0006_room_sashi_uma_type_alter_room_sashi_uma_1_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='return_points',
            field=models.IntegerField(default=30000, verbose_name='返し点'),
        ),
    ]
