# Generated by Django 5.2.4 on 2026-01-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0007_add_return_points_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最終使用時刻'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rate_type',
            field=models.CharField(choices=[('no', 'ノーレート'), ('ten1', 'テンイチ'), ('ten2', 'テンニ'), ('ten3', 'テンサン'), ('ten5', 'テンゴ'), ('pin', 'テンピン'), ('ryanpin', 'テンリャンピン'), ('upin', 'ウーピン'), ('dekapin', 'デカピン'), ('custom', 'カスタム')], default='ten5', max_length=10, verbose_name='レート'),
        ),
        migrations.AlterField(
            model_name='room',
            name='sashi_uma_type',
            field=models.CharField(choices=[('5-10', '5-10 (1位+10, 2位+5, 3位-5, 4位-10)'), ('10-20', '10-20 (1位+20, 2位+10, 3位-10, 4位-20)'), ('10-30', '10-30 (1位+30, 2位+10, 3位-10, 4位-30)'), ('custom', 'カスタム')], default='5-10', max_length=10, verbose_name='サシウマタイプ'),
        ),
    ]
